### ISSUE TITLE
useWindowDimensions Performance Problem

### ISSUE THREAD

**Issue by ruipaulo** [MrLoh/styled-native-components#12]
We had big performance problems that occurred when a device is rotated (landscape<->portrait). This somehow leads to a rerendering of the whole app and thus a lag of 3-5 seconds for our app on modern iOS and Android devices.

The problem was introduced in 4b1884d590ada73db97fa58a8344527da88a8c07 where the custom useWindowDimensions hook was replaced by the standard one from react-native.

My guess is, that because useWindowDimensions is used in src/make-styles.tsx the whole theme/app gets rerendered and the native useWindowDimensions hook has slightly different firing characteristics compared to the previous custom implementation.

**Comment by MrLoh** [comment]
@ruipaulo I pushed up a PR that should fix this, can you give it a try?

**Comment by MrLoh** [comment]
I merged the fix in, was running into similar problems with the native useWindowDimensions hook

**Comment by ruipaulo** [comment]
@MrLoh Sorry, did not see your comment until now.

**Comment by MrLoh** [comment]
No worries. Hope it also solves your problems.
