### ISSUE TITLE
Warning when calling StyledForwardRefRenderFunction

### ISSUE THREAD

**Issue by jardelbordignon** [MrLoh/styled-native-components#36]
react: 18.2.0
react-native: 0.70.6
react-native-web: ^0.18.10
styled-native-components: ^0.5.0

Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks. You can only call Hooks at the top level of your React function.

at StyledForwardRefRenderFunction (webpack://mobile/./node_modules/styled-native-components/dist/styled-native-components.esm.js?:1:20003

Thanks

**Comment by MrLoh** [comment]
I can't reproduce this, could you provide an example of what of your code is triggering this.
